### PR TITLE
Update README to account for frozensets

### PR DESCRIPTION
**Pull request by dimaqq**

### CODE REVIEW

**Comment by dimaqq** [comment]
cc @tonyandrewmeyer

**Comment by dimaqq** [comment]
Ugh, opened a PR to myself 🙈

**Comment by tonyandrewmeyer** [comment]
😄 Submitting this upstream would be good, though. It might be better if we get rid of the test function and move all that code to the top level (of the code block). That way the test-readme check would catch this (the subscripting part at least). That also seems more consistent with the rest of the readme.

**Comment by dimaqq** [comment]
I think it is already fixed upstream

**Pull request closed without merging**
